### PR TITLE
filtering completion list

### PR DESCRIPTION
**Pull request by veksha**
some LSP servers return completion list without filtering, so client app must implement filtering on its side.
- tested with JS server (typescript-language-server)
- not breaking anything for others (tested with Python lsp and Nim lsp servers)

Recording 2022-05-19 at 10 53 06

### CODE REVIEW

**Comment by CudaText-addons** [comment]
do you filter by __entire__ word at caret, of by __lefter part of word__ (lefter than caret)?

**Comment by veksha** [comment]
left side,
i copied some code from `def do_complete`

**Comment by CudaText-addons** [comment]
Does LSP protocol has the field for such feature- 'server filers result list by current word'? if not, can we post the wish to LSP github?

**Comment by veksha** [comment]
As i understand some server implemented filtering on server side, others don't and left it to client.
LSP protocol supports server-side filtering but recommends client-side filtering.

SublimeText has a term for this client-side filtering `DYNAMIC_COMPLETIONS`. if i understand correctly.
[sublimelsp/plugin/documents.py]

but it is enabled only if response has isIncomplete=False in it.
(is list of items is complete or filtered already)

(https://github.com/sublimelsp/LSP/blob/e14bf5de0cacabea9545cf88f27cea7fa8e4e840/plugin/documents.py#L717-L718)
```python
                if response.get("isIncomplete", False):
                    flags |= sublime.DYNAMIC_COMPLETIONS
```

I tested three servers (js nim py), neither of them has this value as True at any case (at starting of a word, or at the middle). So i guess we can just filter completionlist on client side for every server just in case.

**Comment by Alexey-T** [comment]
Ok, thanks

**Pull request merged**
