### PR TITLE
snippetSupport: True

### PR DESCRIPTION
**Pull request by veksha**
enabled snippetSupport for completion.
test.

### CODE REVIEW

**Comment by Alexey-T** [comment]
It can be closed? i cannot see file-changes now in GH.

**Comment by veksha** [comment]
maybe because it was not rebased onto main?
rebased now.

why close?

**Comment by Alexey-T** [comment]
now i see file-changes.

**Comment by veksha** [comment]
copied `snippet.py` from cuda_snippets addon and used it like this:
```python
snippet = Snippet(text=text)
snippet.insert(ed)
```

and it works!
time to test, @Alexey-T.

**Comment by Alexey-T** [comment]
how can I test it, what servers return snippets?

**Comment by veksha** [comment]
clangd, for example, it can return snippets with tab-stops and/or placeholders

**Comment by veksha** [comment]
image

**Comment by veksha** [comment]
image

**Comment by Alexey-T** [comment]
Looks good, soon I will test it (with clangd too).

**Comment by Alexey-T** [comment]
`ed.replace(x1,y1,x2,y2, "") # replace range with emptiness`

why not ed.delete(x1,y1,x2,y2) ?

**Comment by Alexey-T** [comment]
patch seems OK, let's apply. what is not finished (site shows 'this pull res is still work in progress')

**Comment by veksha** [comment]
> patch seems OK, let's apply

changed "replace" to "delete".
ready.
please test and merge.

**Comment by veksha** [comment]
@Alexey-T you can add copyright message somewhere in readme (about snippet.py file) if you want. (this code is not mine obviously)

**Comment by Alexey-T** [comment]
done.

**Pull request merged**
