### PR TITLE
Signature.hint.2

### PR DESCRIPTION
**Pull request by CudaText-addons**

### CODE REVIEW

**Comment by veksha** [comment]
I forgot to set API version in .inf.
can you set correct value there? @Alexey-T

**Comment by Alexey-T** [comment]
but old Cud is supported ok, just 'on_caret_slow' will be ignored?

**Comment by veksha** [comment]
unknown events just ignored? then maybe OK.

**Comment by Alexey-T** [comment]
@veksha i made micro changes in dlg.py, please sync ur file.

**Pull request merged**
