### PR TITLE
fix: semantic tokens don't work when caret is in comments

### PR DESCRIPTION
**Pull request by veksha**

### CODE REVIEW

**Comment by veksha** [comment]
another commit: fix brackets for autocompletion of constructors (brackets were not inserted)

**Comment by Alexey-T** [comment]
snakeCaseNames in python? better lower_case_names.

**Comment by veksha** [comment]
some funcs in client.py must be snakeCase, because they are "name" (see `_action_by_name` func) and this name must be equal to names in LSP spec.
but `semanticTokens` is not called by name anymore (in last commit), so it's ok to change it. i will change.

**Comment by veksha** [comment]
camelCase to snake_case, actually.

**Pull request merged**
