### PR TITLE
fix bash completion

### PR DESCRIPTION
**Pull request by veksha**
Bash server autocompletion was broken by recent optimization. FIXED.
\+ better error handling.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Thanks!
BTW, micro issue: when I have caret inside a word:
`a|bcd` and call autocomplete to replace `abcd` with another word, I see the flickering: how old word is deleted + new word is inserted.

**Comment by veksha** [comment]
i think it's `ed.delete` followed by `ed.insert`.
two on_change events are happening. (2x times more repaint events and LSP events, hence the flickering)
i can try to use ed.replace.

but maybe there is a way to lock editor from repaint and firing `on_change` events, then make edits, then unlock?
(this way can be more simple, no need to calculate additional stuff)

**Comment by Alexey-T** [comment]
```
>>> ed.lock()
>>> ed.unlock()
```
but it may show hourglass icon!

**Comment by Alexey-T** [comment]
made new issue #147 . let's talk there.

**Pull request merged**
