### PR TITLE
added option to reuse Complete From Text

### PR DESCRIPTION
**Pull request by veksha**
resolves https://github.com/CudaText-addons/cuda_lsp/issues/152

### CODE REVIEW

**Comment by Alexey-T** [comment]
see my review-comment.

**Comment by Alexey-T** [comment]
if len==2, then use `tab_title` empty.

**Comment by veksha** [comment]
> see my review-comment.

i dont see it

**Comment by veksha** [comment]
> if len==2, then use `tab_title` empty.

did you mean this code?
```python
parts = item.split('|')
if len(parts) == 3:
    _, label, tab_name = parts
```
i think it's always 3.

**Comment by Alexey-T** [comment]
review-cmt even has your name tagged!
cc

**Comment by Alexey-T** [comment]
it's not always 3. last pipe-char is added here
```python
    def search_tab(w):
        if option_what_editors in [1, 2]:
            tabs_found = []
            for i, words_by_tabs_ in enumerate(words_by_tabs):
                if w in words_by_tabs_:
                    tabs_found.append(i)
            if tabs_found:
                return '|' + '; '.join([tab_titles[tf] for tf in tabs_found])
            return ''
        else:
            return ''
```

**Comment by veksha** [comment]
i don't see review. github bug? i see it on screenshot only.

**Comment by Alexey-T** [comment]
github bug I think. see my above comment

**Comment by veksha** [comment]
fixed

**Comment by veksha** [comment]
no. i see bug. wait

**Pull request merged**
