### PR TITLE
Add config option to disable markers

### PR DESCRIPTION
**Pull request by DUOLabs333**

### CODE REVIEW

**Comment by veksha** [comment]
also the following files in a `readme` folder can be updated: `history.txt`, `options_description.md`

**Comment by Alexey-T** [comment]
```
        if self.use_markers:
            # insert new markers
            for m in zero_markers:
...
```
it is possible to insert 
```
if not self.use_markers:
    return
```
which is better. it makes DIFF small.

**Comment by DUOLabs333** [comment]
@veksha Done.

**Comment by Alexey-T** [comment]
@veksha, please test it before I apply.

**Comment by veksha** [comment]
Works for me.

**Comment by Alexey-T** [comment]
I did not test it, so i listen to veksha and apply the PR.

**Comment by veksha** [comment]
@DUOLabs333 thanks for your work.

**Pull request merged**
